from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import datetime
import io
import matplotlib.pyplot as plt


def generate_report(stats, session_time):

    # ---------- CREATE GRAPH ----------
    exercises = list(stats.keys())
    reps = list(stats.values())

    chart_buffer = io.BytesIO()

    plt.figure(figsize=(6,4))
    plt.bar(exercises, reps, color=["cyan","orange","lime"])
    plt.title("Workout Distribution")
    plt.xlabel("Exercise")
    plt.ylabel("Reps")

    plt.savefig(chart_buffer, format="png")
    plt.close()

    chart_buffer.seek(0)

    chart_image = ImageReader(chart_buffer)

    # ---------- CREATE PDF ----------
    buffer = io.BytesIO()

    c = canvas.Canvas(buffer, pagesize=letter)

    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 22)
    c.drawString(180, height - 60, "Workout Report")

    today = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, f"Date: {today}")
    c.drawString(50, height - 120, f"Session Time: {session_time}")

    # ---------- SUMMARY ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 160, "Workout Summary")

    y = height - 190

    for exercise, reps in stats.items():
        c.setFont("Helvetica", 12)
        c.drawString(70, y, f"{exercise.capitalize()} : {reps} reps")
        y -= 25

    # ---------- CHART ----------
    c.drawImage(chart_image, 50, height - 420, width=400, height=200)

    # ---------- INSIGHTS ----------
    total_reps = sum(stats.values())
    most_done = max(stats, key=stats.get)

    insights = [
        f"Total reps performed: {total_reps}",
        f"Most performed exercise: {most_done.capitalize()}",
    ]

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 450, "Workout Insights")

    y = height - 480

    for text in insights:
        c.setFont("Helvetica", 12)
        c.drawString(70, y, text)
        y -= 20

    # ---------- SUGGESTIONS ----------
    suggestions = []

    if stats["squat"] < 10:
        suggestions.append("Increase squat reps for stronger legs.")

    if stats["curl"] < 10:
        suggestions.append("Add more curls to improve arm endurance.")

    if stats["pushup"] < 10:
        suggestions.append("Practice pushups for upper body strength.")

    if total_reps > 30:
        suggestions.append("Great workout! Consider stretching after exercise.")

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 560, "AI Suggestions")

    y = height - 590

    for text in suggestions:
        c.setFont("Helvetica", 12)
        c.drawString(70, y, f"- {text}")
        y -= 20

    # Footer
    c.setFont("Helvetica", 10)
    c.drawString(50, 40, "Generated by AI Physio Coach")

    c.save()

    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes